/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.chezis.lab2.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Chezis P
 */
public class SelectionPage extends javax.swing.JFrame {

    /**
     * Creates new form SelectionPage
     */
    public SelectionPage() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBai1_1 = new javax.swing.JButton();
        btnBai1_2 = new javax.swing.JButton();
        btnBai2 = new javax.swing.JButton();
        btnBai3 = new javax.swing.JButton();
        btnBai4 = new javax.swing.JButton();
        txtMainText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBai1_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBai1_1.setText("Bài 1 - 1");
        btnBai1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBai1_1ActionPerformed(evt);
            }
        });

        btnBai1_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBai1_2.setText("Bài 1 - 2");
        btnBai1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBai1_2ActionPerformed(evt);
            }
        });

        btnBai2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBai2.setText("Bài 2");
        btnBai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBai2ActionPerformed(evt);
            }
        });

        btnBai3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBai3.setText("Bài 3");
        btnBai3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBai3ActionPerformed(evt);
            }
        });

        btnBai4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBai4.setText("Bài 4");
        btnBai4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBai4ActionPerformed(evt);
            }
        });

        txtMainText.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtMainText.setText("Chọn bài muốn xem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBai1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBai1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBai3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBai2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBai4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(txtMainText)
                        .addContainerGap(113, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtMainText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBai1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBai1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBai2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBai4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBai3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBai1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBai1_1ActionPerformed
        setVisible(false);
        Bai1_1 panel = new Bai1_1();
        panel.setResizable(false);
        panel.show();
    }//GEN-LAST:event_btnBai1_1ActionPerformed

    private void btnBai1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBai1_2ActionPerformed
        setVisible(false);
        Bai1_2 panel = new Bai1_2();
        panel.setResizable(false);
        panel.show();
    }//GEN-LAST:event_btnBai1_2ActionPerformed

    private void btnBai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBai2ActionPerformed
        setVisible(false);
        Bai2 panel = new Bai2();
        panel.setResizable(false);
        panel.show();
    }//GEN-LAST:event_btnBai2ActionPerformed

    private void btnBai3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBai3ActionPerformed
        setVisible(false);
        Bai3 panel = new Bai3();
        panel.setResizable(false);
        panel.show();
    }//GEN-LAST:event_btnBai3ActionPerformed

    private void btnBai4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBai4ActionPerformed
//        setVisible(false);
//        JOptionPane.showMessageDialog(this, "Tính năng này chưa hoàn thiện !", "Cảnh Báo", JOptionPane.ERROR_MESSAGE);
//        setVisible(true);
        setVisible(false);
        Bai4 panel = new Bai4();
        panel.setResizable(false);
        panel.show();
    }//GEN-LAST:event_btnBai4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBai1_1;
    private javax.swing.JButton btnBai1_2;
    private javax.swing.JButton btnBai2;
    private javax.swing.JButton btnBai3;
    private javax.swing.JButton btnBai4;
    private javax.swing.JLabel txtMainText;
    // End of variables declaration//GEN-END:variables
}
